// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/request.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/request.proto

It has these top-level messages:
	ServiceRequest
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceRequest struct {
	Query         string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	PageNumber    int32  `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage int32  `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
}

func (m *ServiceRequest) Reset()                    { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()               {}
func (*ServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ServiceRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ServiceRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceRequest)(nil), "service.ServiceRequest")
}

func init() { proto.RegisterFile("service/request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x87, 0x0a, 0x2b, 0xe5, 0x73, 0xf1, 0x05, 0x43, 0x98, 0x41, 0x10, 0x05, 0x42,
	0x22, 0x5c, 0xac, 0x85, 0xa5, 0xa9, 0x45, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x3c, 0x17, 0x77, 0x41, 0x62, 0x7a, 0x6a, 0x7c, 0x5e, 0x69, 0x6e, 0x52, 0x6a, 0x91,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x17, 0x48, 0xc8, 0x0f, 0x2c, 0x22, 0xa4, 0xc6, 0xc5,
	0x5f, 0x94, 0x5a, 0x5c, 0x9a, 0x53, 0x12, 0x5f, 0x90, 0x5a, 0x14, 0x0f, 0x92, 0x90, 0x60, 0x06,
	0x2b, 0xe2, 0x85, 0x08, 0x07, 0xa4, 0x16, 0x05, 0x24, 0xa6, 0xa7, 0x26, 0xb1, 0x81, 0x1d, 0x60,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x67, 0x1a, 0x09, 0x70, 0x99, 0x00, 0x00, 0x00,
}
